server:
  port: 55149
spring:
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
    hibernate:
      ddl-auto: update
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
  application:
    name: credit-card-verification-service
  cloud:
    stream:
      function:
        definition: verifyCreditCardApplication
      bindings:
        verifyCreditCardApplication-in-0:
          destination: CreditCardApplication
          group: creditCard
        verifyCreditCardApplication-out-0:
          destination: creditCardVerification
          group: creditCard
